### PR TITLE
[#WEB-20373] Updates knightlab timeline ressources

### PR DESCRIPTION
**Pull request by Utopiad**
Knightlab link was not up-to-date any more, so following Bart instructions this PR fixes it.

I don't know how to test this though.

### CODE REVIEW

**Review by arthurjamain — APPROVED** [review]
oof, hadn't seen this repo in a while :)

**Comment by Utopiad** [comment]
Do you know how to test this? Am talking with Ismael to see how I could test this on a dev server

**Comment by arthurjamain** [comment]
Devserver may well be the easiest way.

**Comment by Utopiad** [comment]
Hurray, it works!

You'll find a preview here to see if it fits to your expectations.
https://sketchfab-timeline.dev.fatshader.com/about

_Warning: first loadings might be slow. If you get an error page because of time out, reload it again and it should work._

In short, the previous timeline.js version we used is no longer available so had to update resources which are not an npm package because we use our own theme.
I don't remember all the little details of changes that were made to this element initially to make it our own, if I missed something please tell me.

**Comment by Utopiad** [comment]
Bart just gave me his approval
image

@pierreant-p is the reference branch for Github Pages on this repo `master` or `gh-page`?

**Comment by arthurjamain** [comment]
Title/commit typo

**Pull request merged**
